# ./.github/workflows/run-top-model-bot.yml
# This workflow runs the main_with_no_framework.py script, configured for the Top Model Bot.

name: Run Top Model Bot

on:
  # Runs every hour
  schedule:
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Force regenerate lock file
        run: |
          rm -f poetry.lock
          poetry lock
      
      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root
      
      - name: Run Top Model Bot
        env:
          PYTHONPATH: .
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          METACULUS_API_KEY: ${{ secrets.METACULUS_API_KEY }}
          # The SEARCH_PROVIDER_API_KEY is optional if web scraping works reliably
          # SEARCH_PROVIDER_API_KEY: ${{ secrets.SEARCH_PROVIDER_API_KEY }}
        run: poetry run python main_with_no_framework.py

